repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
        files: ^requirements.txt$
      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.18
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--frozen", "--output-file=requirements.txt", "--all-extras", "--no-default-groups", "--no-hashes", "--quiet"]

default_language_version:
    python: python3.14
