[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "modmail"
description = "A Discord Modmail bot."
authors = [
    {name = "Taku", email = "taku@modmail.dev"},
    {name = "FourJr (Former, Inactive)", email = "no-email@example.com"},
    {name = "Kyber (Former, Inactive)", email = "no-email@example.com"},
]
readme = "README.md"
requires-python = ">=3.13"
license = {text = "AGPL-3.0-or-later"}
dynamic = ["version"]

keywords = ["discord", "discord-bot", "modmail", "python", "discord.py", "discord-modmail"]
classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.13",
    "Topic :: Communications :: Chat",
    "Topic :: Communications :: Conferencing",
    "Typing :: Typed",
]

dependencies = [
    "discord.py==2.5.2",
    "beanie[srv]~=1.29.0",
    "rich~=13.9.4",
    "pydantic[dotenv]<2.11,>=2.10.6",
    "pydantic-settings<2.9,>=2.8.1",
    "packaging",  # For version parsing.
]

[project.optional-dependencies]
speed = [
    "discord.py[speed]==2.5.2",
    "uvloop>=0.21.0; platform_system != \"Windows\"",
]

[tool.pdm.dev-dependencies]
lint = [
    "black>=25.1.0",
    "pyright>=1.1.396",
    "isort>=6.0.1",
]
tools = [
    "pre-commit<5,>=4.1.0",
]
debug = [
    "jishaku<2.7,>=2.6.0",
]

[project.urls]
homepage = "https://github.com/modmail-dev/modmail"
repository = "https://github.com/modmail-dev/modmail"

# PDM build system configs.
[tool.pdm]
distribution = true

[tool.pdm.version]
source = "file"
path = "modmail/__init__.py"

[tool.pdm.build]
includes = ["modmail"]

[tool.isort]
profile = "black"
line_length = 115
combine_as_imports = true
combine_star = true

# Using black as linter for now, may switch to ruff in the future.
[tool.black]
line-length = 115
target-version = ['py313']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.env
  | venv
  | env
  | __pycache__
  | dist
)/
'''

[tool.pyright]
exclude = [
    "**/__pycache__",
    "**/venv",
    "**/env",
    "**/.venv",
    "**/.env",
    "dist",
]
reportMissingImports = true
reportUnnecessaryTypeIgnoreComment = "error"
pythonVersion = "3.13"
pythonPlatform = "All"
typeCheckingMode = "strict"
