[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "modmail"
description = "A Discord Modmail bot."
authors = [
    {name = "Taaku18", email = "taku@modmail.dev"},
]
readme = "README.md"
requires-python = ">=3.12"
license = "AGPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
dynamic = ["version"]

keywords = ["discord", "discord-bot", "modmail", "python", "discord.py", "discord-modmail"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Environment :: Console",
    "Natural Language :: English",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Communications :: Chat",
    "Topic :: Communications :: Conferencing",
    "Typing :: Typed",
]

dependencies = [
    "discord.py==2.5.2",
    "rich~=13.9.4",
    "pydantic[dotenv]<2.11,>=2.10.6",
    "pydantic-settings<2.9,>=2.8.1",
    "packaging",  # For version parsing.
    "pyyaml~=6.0.2",
    "fluent-runtime<0.5,>=0.4.0",
]

[project.optional-dependencies]
speed = [
    "discord.py[speed]==2.5.2",
    "uvloop>=0.21.0; platform_system != \"Windows\"",
]
sqlite = [
    "sqlalchemy[asyncio,aiosqlite]<2.1,>=2.0.39",
    "alembic<1.16,>=1.15.1"
]
mongodb = [
    "beanie[srv] @ git+https://github.com/Taaku18/beanie@change-toml-dependency",
]
all = [
    "modmail[speed,sqlite,mongodb]",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
    "pyright>=1.1.396",
    "isort>=6.0.1",
    "pre-commit<5,>=4.1.0",
    "pytest<9,>=8.3.5",
    # When updating pytest plugins, update it below in the pytest "required_plugins" section too
    "pytest-mock<4,>=3.14.0",
    "pytest-asyncio<1,>=0.25.3",
    "pytest-cov<7,>=6.0.0",
    "mock"  # used by pytest-mock
]
debug = [
    "jishaku<2.7,>=2.6.0",
]

[project.urls]
Documentation = "https://docs.modmail.dev"
Repository = "https://github.com/modmail-dev/modmail"
Issues = "https://github.com/modmail-dev/modmail/issues"
Changelog = "https://github.com/modmail-dev/Modmail/blob/master/CHANGELOG.md"
# TODO: add Funding = "..."

# PDM build system configs.
[tool.pdm]
distribution = true

[tool.pdm.version]
source = "file"
path = "modmail/__init__.py"

[tool.pdm.build]
includes = ["modmail"]

[tool.isort]
profile = "black"
line_length = 115
combine_as_imports = true
combine_star = true

[tool.ruff]
line-length = 115

[tool.ruff.lint]
select = [
    "E", "W",  # pycodestyle
    "F",       # pyflakes
    "ANN",     # flake8-annotations
    "ASYNC",   # flake8-async
    "S",       # flake8-bandit
    "B",       # flake8-bugbear
    "A",       # flake8-builtins
    "DTZ",     # flake8-datetimez
    "LOG",     # flake8-logging
    "G",       # flake8-logging-format
    "T20",     # flake8-print
    "PT",      # flake8-pytest-style
    "RET",     # flake8-return
    "SIM",     # flake8-simplify
    "PTH",     # flake8-use-pathlib
    "I",       # isort
    "N",       # pep8-naming
#    "DOC",    # pydoclint (preview)
#    "D",      # pydocstyle (TODO: add later + configure, lots of changes)
    "PL",      # pylint
    "UP",      # pyupgrade
    "RUF",     # Ruff-specific rules
]

ignore = [
    "ANN401",  # disallow Any type
    "S101",    # use of assert detected
    "SIM102",  # single if instead of nested if
    "SIM108",  # use of ternary instead of if else
    "PLR0915", # too many statements in function
    "PLR0913", # too many arguments
    "PLR0912", # too many branches
    "PLR0911", # too many return statements
    "PLR5501", # use `elif` instead of `else` then `if`
    "PLW2901", # `for` loop variable `value` overwritten by assignment target
    "RUF012",  # mutable class attributes should be annotated with `typing.ClassVar`
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]  # F403: 'from module import *' used; unable to detect undefined names
"ftl_finder.py" = ["T201"]  # T201: Use of print
"tests/*" = ["D107", "D101", "D100", "D105", "D202", "D102", "D104", "D103", "PLR2004"]  # D*: Missing doc strings, PLR2004: Compare magic number

[tool.pyright]
exclude = [
    "**/__pycache__",
    "**/.tox",
    "**/venv",
    "**/env",
    "**/.venv",
    "**/.env",
    "dist",
]
reportUnnecessaryTypeIgnoreComment = "warning"
reportPropertyTypeMismatch = "error"
pythonVersion = "3.12"
pythonPlatform = "All"
typeCheckingMode = "strict"
executionEnvironments = [
  { root = "tests", reportPrivateUsage = "none", reportFunctionMemberAccess = "none", reportWildcardImportFromLibrary = "none" },
]

[tool.pytest.ini_options]
mock_use_standalone_module = true
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = "--cov=modmail --cov-report html"
testpaths = ["tests"]
required_plugins = ["pytest-mock<4,>=3.14.0", "pytest-asyncio<1,>=0.25.3", "pytest-cov<7,>=6.0.0"]
filterwarnings = [
    "ignore:.*'audioop' is deprecated.*:DeprecationWarning", # discord.py uses audioop, which is deprecated
]

[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:",
    "if \"pytest\" not in sys.modules:",
    "raise NotImplementedError",
    "raise AssertionError",
]

# To run tox development automation: `pip install tox tox-pdm`, then run `tox`.
[tool.tox]
min_version = "4"
requires = ["tox-pdm"]
envlist = ["py12", "py13", "lint", "pyright"]

[tool.tox.env_run_base]
description = "Run test under {base_python}"
groups = ["all", "dev"]
commands = [["pytest"]]

[tool.tox.env.lint]
description = "run linters (pre-commit)"
skip_install = true
deps = ["pre-commit<5,>=4.1.0"]
commands = [["pre-commit", { replace = "posargs", default = ["run", "--all-files"], extend = true} ]]

[tool.tox.env.pyright]
description = "run pyright"
groups = ["all"]
commands = [
    ["pyright", { replace = "posargs", extend = true}],
]
