"""init

Revision ID: 422824ed6c24
Revises:
Create Date: 2025-03-14 06:51:11.844141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "422824ed6c24"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("last_ran_version", sa.String(length=32), nullable=True),
        sa.Column("main_category_id", sa.Integer(), nullable=True),
        sa.Column("fallback_category_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("online", "idle", "dnd", "offline", name="statustype"), nullable=True),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_settings")),
        sa.UniqueConstraint("bot_id", name=op.f("uq_settings_bot_id")),
    )
    op.create_table(
        "activity",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("playing", "streaming", "listening", "watching", "custom", "competing", name="activitytype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["settings.bot_id"], name=op.f("fk_activity_bot_id_settings"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_activity")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity")
    op.drop_table("settings")
    # ### end Alembic commands ###
