"""init

Revision ID: 692408469f9d
Revises:
Create Date: 2025-03-13 02:00:08.498711

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "692408469f9d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("playing", "streaming", "listening", "watching", "custom", "competing", name="activitytype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity")),
    )
    op.create_table(
        "settings",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("last_ran_version", sa.String(length=32), nullable=True),
        sa.Column("main_category_id", sa.Integer(), nullable=True),
        sa.Column("fallback_category_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("online", "idle", "dnd", "offline", name="statustype"), nullable=True),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activity.id"], name=op.f("fk_settings_activity_id_activity"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_settings")),
        sa.UniqueConstraint("bot_id", name=op.f("uq_settings_bot_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_table("activity")
    # ### end Alembic commands ###
