"""add slash_last_synced_version col

Revision ID: 7aae73524103
Revises: 422824ed6c24
Create Date: 2025-03-17 03:10:51.171388

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aae73524103"
down_revision: Union[str, None] = "422824ed6c24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("slash_last_synced_version", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "slash_last_synced_version")
    # ### end Alembic commands ###
