"""init

Revision ID: 8b4495d3709b
Revises:
Create Date: 2025-04-21 05:23:00.230961
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b4495d3709b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("last_ran_version", sa.String(length=32), nullable=True),
        sa.Column("last_ran_locale", sa.String(length=8), nullable=True),
        sa.Column("last_slash_synced_version", sa.String(length=32), nullable=True),
        sa.Column("last_slash_minimum_permission_int", sa.Integer(), nullable=True),
        sa.Column("main_category_id", sa.Integer(), nullable=True),
        sa.Column("fallback_category_id", sa.Integer(), nullable=True),
        sa.Column("log_channel_id", sa.Integer(), nullable=True),
        sa.Column("storage_channel_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("online", "idle", "dnd", "offline", name="statustype"), nullable=True),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_settings")),
    )
    op.create_table(
        "thread_user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_thread_user")),
    )
    op.create_table(
        "activity",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("playing", "streaming", "listening", "watching", "custom", "competing", name="activitytype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["settings.bot_id"],
            name=op.f("fk_activity_bot_id_settings"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_activity")),
    )
    op.create_table(
        "profile",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("profile_type", sa.Enum("user", "role", name="profiletype"), nullable=False),
        sa.Column(
            "access_level", sa.Enum("everyone", "staff", "manager", "admin", name="accesslevel"), nullable=True
        ),
        sa.Column("tag", sa.String(length=128), nullable=True),
        sa.Column("colour", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["settings.bot_id"],
            name=op.f("fk_profile_bot_id_settings"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bot_id", "profile_id", "profile_type", name=op.f("pk_profile")),
    )
    op.create_table(
        "thread",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=12), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("closed_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "closed_by_command", "closed_by_deletion", name="threadstatus"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("nsfw", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["closed_by_id"],
            ["thread_user.user_id"],
            name=op.f("fk_thread_closed_by_id_thread_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["thread_user.user_id"],
            name=op.f("fk_thread_created_by_id_thread_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("bot_id", "key", name=op.f("pk_thread")),
        sa.UniqueConstraint("bot_id", "channel_id", name="uq_thread_channel"),
    )
    op.create_table(
        "permission_override",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("profile_type", sa.Enum("user", "role", name="profiletype"), nullable=False),
        sa.Column("command_name", sa.String(length=256), nullable=False),
        sa.Column("override_value", sa.Enum("allow", "deny", name="permissionoverridevalue"), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id", "profile_id", "profile_type"],
            ["profile.bot_id", "profile.profile_id", "profile.profile_type"],
            name="fk_permission_override_profile",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "bot_id", "profile_id", "profile_type", "command_name", name=op.f("pk_permission_override")
        ),
    )
    op.create_table(
        "thread_message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("thread_key", sa.String(length=12), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=4096), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("edited_by_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.Enum("reply", "dm", "internal", name="threadmessagetype"), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["thread_user.user_id"],
            name=op.f("fk_thread_message_author_id_thread_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bot_id", "thread_key"],
            ["thread.bot_id", "thread.key"],
            name="fk_thread_message_thread",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["thread_user.user_id"],
            name=op.f("fk_thread_message_deleted_by_id_thread_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["edited_by_id"],
            ["thread_user.user_id"],
            name=op.f("fk_thread_message_edited_by_id_thread_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread_message")),
        sa.UniqueConstraint("bot_id", "thread_key", "message_id", name="uq_thread_message"),
    )
    op.create_table(
        "thread_recipient",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("thread_key", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id", "thread_key"],
            ["thread.bot_id", "thread.key"],
            name="fk_thread_recipient_thread",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["thread_user.user_id"],
            name=op.f("fk_thread_recipient_user_id_thread_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread_recipient")),
        sa.UniqueConstraint("bot_id", "thread_key", "user_id", name="uq_thread_recipient"),
    )
    op.create_table(
        "thread_dm_message",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("thread_message_ref_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["thread_user.user_id"],
            name=op.f("fk_thread_dm_message_recipient_id_thread_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["thread_message_ref_id"],
            ["thread_message.id"],
            name=op.f("fk_thread_dm_message_thread_message_ref_id_thread_message"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_thread_dm_message")),
        sa.UniqueConstraint("message_id", "thread_message_ref_id", name="uq_thread_dm_message"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thread_dm_message")
    op.drop_table("thread_recipient")
    op.drop_table("thread_message")
    op.drop_table("permission_override")
    op.drop_table("thread")
    op.drop_table("profile")
    op.drop_table("activity")
    op.drop_table("thread_user")
    op.drop_table("settings")
    # ### end Alembic commands ###
