"""add permission groups

Revision ID: a363b927c5ed
Revises: 7aae73524103
Create Date: 2025-03-18 17:12:30.354663

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a363b927c5ed"
down_revision: Union[str, None] = "7aae73524103"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_group",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("group_type", sa.Enum("user", "role", name="permissiongrouptype"), nullable=False),
        sa.Column(
            "level", sa.Enum("everyone", "staff", "manager", "admin", name="permissionlevel"), nullable=True
        ),
        sa.PrimaryKeyConstraint("bot_id", "group_id", "group_type", name="permission_group_pk"),
    )
    op.create_table(
        "permission_group_override",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("group_type", sa.Enum("user", "role", name="permissiongrouptype"), nullable=False),
        sa.Column("command_name", sa.String(length=256), nullable=False),
        sa.Column("override_value", sa.Enum("allow", "deny", name="permissionoverridetype"), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id", "group_id", "group_type"],
            ["permission_group.bot_id", "permission_group.group_id", "permission_group.group_type"],
            name="fk_permission_group_override_permission_group",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "bot_id", "group_id", "group_type", "command_name", name="pk_permission_group_override"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permission_group_override")
    op.drop_table("permission_group")
    # ### end Alembic commands ###
