"""init

Revision ID: ec2d46746dcd
Revises:
Create Date: 2025-05-05 13:15:14.884603
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec2d46746dcd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("last_ran_version", sa.String(length=32), nullable=True),
        sa.Column("last_ran_locale", sa.String(length=8), nullable=True),
        sa.Column("last_slash_synced_version", sa.String(length=32), nullable=True),
        sa.Column("last_slash_minimum_permission_int", sa.Integer(), nullable=True),
        sa.Column("main_category_id", sa.Integer(), nullable=True),
        sa.Column("fallback_category_id", sa.Integer(), nullable=True),
        sa.Column("log_channel_id", sa.Integer(), nullable=True),
        sa.Column("storage_channel_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("online", "idle", "dnd", "offline", name="statustype"), nullable=True),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_settings")),
    )
    op.create_table(
        "ticket_user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_ticket_user")),
    )
    op.create_table(
        "activity",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("playing", "streaming", "listening", "watching", "custom", "competing", name="activitytype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["settings.bot_id"],
            name=op.f("fk_activity_bot_id_settings"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_activity")),
    )
    op.create_table(
        "profile",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("profile_type", sa.Enum("user", "role", name="profiletype"), nullable=False),
        sa.Column(
            "access_level", sa.Enum("everyone", "staff", "manager", "admin", name="accesslevel"), nullable=True
        ),
        sa.Column("tag", sa.String(length=128), nullable=True),
        sa.Column("colour", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["settings.bot_id"],
            name=op.f("fk_profile_bot_id_settings"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bot_id", "profile_id", "profile_type", name=op.f("pk_profile")),
    )
    op.create_table(
        "ticket",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=12), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("closed_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "closed_by_command", "closed_by_deletion", name="ticketstatus"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("nsfw", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["closed_by_id"],
            ["ticket_user.user_id"],
            name=op.f("fk_ticket_closed_by_id_ticket_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["ticket_user.user_id"],
            name=op.f("fk_ticket_created_by_id_ticket_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("bot_id", "key", name=op.f("pk_ticket")),
        sa.UniqueConstraint("bot_id", "channel_id", name="uq_ticket_channel"),
    )
    op.create_table(
        "permission_override",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("profile_type", sa.Enum("user", "role", name="profiletype"), nullable=False),
        sa.Column("command_name", sa.String(length=256), nullable=False),
        sa.Column("override_value", sa.Enum("allow", "deny", name="permissionoverridevalue"), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id", "profile_id", "profile_type"],
            ["profile.bot_id", "profile.profile_id", "profile.profile_type"],
            name="fk_permission_override_profile",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "bot_id", "profile_id", "profile_type", "command_name", name=op.f("pk_permission_override")
        ),
    )
    op.create_table(
        "ticket_message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("ticket_key", sa.String(length=12), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=4096), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("edited_by_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "type", sa.Enum("reply", "dm", "internal", "close", "sclose", name="ticketmessagetype"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["ticket_user.user_id"],
            name=op.f("fk_ticket_message_author_id_ticket_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bot_id", "ticket_key"],
            ["ticket.bot_id", "ticket.key"],
            name="fk_ticket_message_ticket",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["ticket_user.user_id"],
            name=op.f("fk_ticket_message_deleted_by_id_ticket_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["edited_by_id"],
            ["ticket_user.user_id"],
            name=op.f("fk_ticket_message_edited_by_id_ticket_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_message")),
        sa.UniqueConstraint("bot_id", "ticket_key", "message_id", name="uq_ticket_message"),
    )
    op.create_index(
        "ix_ticket_message_author", "ticket_message", ["bot_id", "ticket_key", "author_id"], unique=False
    )
    op.create_index("ix_ticket_message_type", "ticket_message", ["bot_id", "ticket_key", "type"], unique=False)
    op.create_table(
        "ticket_recipient",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("ticket_key", sa.String(length=12), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id", "ticket_key"],
            ["ticket.bot_id", "ticket.key"],
            name="fk_ticket_recipient_ticket",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["ticket_user.user_id"],
            name=op.f("fk_ticket_recipient_user_id_ticket_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_recipient")),
        sa.UniqueConstraint("bot_id", "ticket_key", "user_id", name="uq_ticket_recipient"),
    )
    op.create_table(
        "ticket_dm_message",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("ticket_message_ref_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["ticket_user.user_id"],
            name=op.f("fk_ticket_dm_message_recipient_id_ticket_user"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_message_ref_id"],
            ["ticket_message.id"],
            name=op.f("fk_ticket_dm_message_ticket_message_ref_id_ticket_message"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_ticket_dm_message")),
        sa.UniqueConstraint("message_id", "ticket_message_ref_id", name="uq_ticket_dm_message"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_dm_message")
    op.drop_table("ticket_recipient")
    op.drop_index("ix_ticket_message_type", table_name="ticket_message")
    op.drop_index("ix_ticket_message_author", table_name="ticket_message")
    op.drop_table("ticket_message")
    op.drop_table("permission_override")
    op.drop_table("ticket")
    op.drop_table("profile")
    op.drop_table("activity")
    op.drop_table("ticket_user")
    op.drop_table("settings")
    # ### end Alembic commands ###
