"""init

Revision ID: fec4067d17f4
Revises:
Create Date: 2025-03-26 11:38:24.535913

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fec4067d17f4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("profile_type", sa.Enum("user", "role", name="profiletype"), nullable=False),
        sa.Column(
            "access_level", sa.Enum("everyone", "staff", "manager", "admin", name="accesslevel"), nullable=True
        ),
        sa.Column("tag", sa.String(length=128), nullable=True),
        sa.Column("colour", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("bot_id", "profile_id", "profile_type", name="profile_pk"),
    )
    op.create_table(
        "settings",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("last_ran_version", sa.String(length=32), nullable=True),
        sa.Column("last_ran_locale", sa.String(length=8), nullable=True),
        sa.Column("last_slash_synced_version", sa.String(length=32), nullable=True),
        sa.Column("last_slash_minimum_permission_int", sa.Integer(), nullable=True),
        sa.Column("main_category_id", sa.Integer(), nullable=True),
        sa.Column("fallback_category_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("online", "idle", "dnd", "offline", name="statustype"), nullable=True),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_settings")),
        sa.UniqueConstraint("bot_id", name=op.f("uq_settings_bot_id")),
    )
    op.create_table(
        "activity",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("playing", "streaming", "listening", "watching", "custom", "competing", name="activitytype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["settings.bot_id"], name=op.f("fk_activity_bot_id_settings"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("bot_id", name=op.f("pk_activity")),
    )
    op.create_table(
        "permission_override",
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("profile_type", sa.Enum("user", "role", name="profiletype"), nullable=False),
        sa.Column("command_name", sa.String(length=256), nullable=False),
        sa.Column("override_value", sa.Enum("allow", "deny", name="permissionoverridevalue"), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id", "profile_id", "profile_type"],
            ["profile.bot_id", "profile.profile_id", "profile.profile_type"],
            name="fk_permission_override_profile",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "bot_id", "profile_id", "profile_type", "command_name", name="pk_permission_override"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permission_override")
    op.drop_table("activity")
    op.drop_table("settings")
    op.drop_table("profile")
    # ### end Alembic commands ###
