name: pre-commit and checks

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1  # TODO: Switch to https://pre-commit.ci/

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: jakebailey/pyright-action@v1
